Repository TarboniCar/Tarbonicar-FE, pull requests merged in 2025-06, with the labels that each got.

#4 [FEAT] 확인, 취소 모달 구현
  src/App.jsx
  src/components/ConfirmDialog.jsx
  src/pages/ModalSample.jsx
Labels: FEAT

#6 [FEAT] : 헤더 반응형 구현
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/Imgs/ds
  src/assets/imgs/Logo.png
  src/assets/imgs/LogoutIcon.png
  src/assets/imgs/Sahuru.png
  src/assets/imgs/profileIcon.png
  src/components/Header.jsx
  src/components/ds
  src/styles/animation.js
Labels: FEAT

#8 [FEAT] 게시글 작성 페이지 구현
  package-lock.json
  package.json
  src/App.jsx
  src/pages/ArticleWrite.jsx
Labels: FEAT

#12 [REFAC] 게시글 작성 시 이미지 등록 기능 및 카테고리 조회 수정
  src/pages/ArticleWrite.jsx
Labels: REFAC

#13 [FEAT] 게시판 리스트 화면 구현
  package-lock.json
  package.json
  src/App.jsx
  src/assets/Svgs/check.svg
  src/assets/Svgs/comment.svg
  src/assets/Svgs/ds
  src/assets/Svgs/like.svg
  src/assets/Svgs/refresh.svg
  src/assets/Svgs/uncheck.svg
  src/assets/Svgs/unlike.svg
  src/assets/imgs/check.png
  src/assets/imgs/uncheck.png
  src/components/ArticleFilter/ArticleFilter.jsx
  src/components/ArticleFilter/CheckboxGroup.jsx
  src/components/ArticleListItem.jsx
  src/pages/ArticleList.jsx
  src/pages/ds
Labels: FEAT

#19 [SETTING] : Axios Instance 설정
  src/api/AxiosInstance.js
  src/api/ds
Labels: SETTING

#22 [FEAT] : 메인화면 API 연동
  src/api/main.js
  src/pages/Main.jsx
Labels: FEAT

#25 [FEAT] 게시글 리스트 연동 및 필터 연결
  package-lock.json
  package.json
  src/api/ArticleApi.js
  src/api/CategoryApi.js
  src/assets/Svgs/arrow_down.svg
  src/assets/imgs/arrow_down.png
  src/components/ArticleFilter/ArticleFilter.jsx
  src/components/ArticleFilter/CheckboxGroup.jsx
  src/components/ArticleListItem.jsx
  src/components/DropdownBox.jsx
  src/pages/ArticleList.jsx
  src/utils/timeForToday.js
Labels: FEAT

#27 [FEAT] 게시글 댓글 화면 구현
  src/api/articleApi.js
  src/api/articleView.js
  src/api/articleWrite.js
  src/api/categoryApi.js
  src/api/commentApi.js
  src/api/imageUploadApi.js
  src/components/ArticleFilter.jsx
  src/components/CheckboxGroup.jsx
  src/components/CommentInput.jsx
  src/components/CommetListItem.jsx
  src/pages/ArticleList.jsx
  src/pages/ArticleView.jsx
  src/pages/ArticleWrite.jsx
  src/utils/timeForToday.js
Labels: FEAT

#28 [FEAT] 로그인 페이지 구현
  src/App.jsx
  src/assets/imgs/check2.svg
  src/assets/imgs/emailIcon.svg
  src/assets/imgs/kakaoIcon.svg
  src/assets/imgs/passwordIcon.svg
  src/pages/Login.jsx
Labels: FEAT

#32 [STYLE] : 파일명 수정
  src/components/Header.jsx
  src/components/RegisterHeader.jsx
  src/pages/Main.jsx
Labels: FIX

#34 [FEAT] 회원가입 페이지 구현
  src/App.jsx
  src/pages/Signup.jsx
Labels: FEAT

#36 [FEAT] 좋아요 토글 기능 연동
  src/api/articleApi.js
  src/pages/ArticleView.jsx
  src/pages/ArticleWrite.jsx
Labels: FEAT

#38 [FIX] 게시글 작성 페이지 수정 기능 구현
  src/api/articleApi.js
  src/pages/ArticleWrite.jsx
Labels: FIX

#39 [FEAT] 회원가입, 로그인 API 연동
  .gitignore
  src/App.jsx
  src/api/memberApi.js
  src/pages/KakaoRedirect.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
  vite.config.js
Labels: FEAT

#47 [FEAT] 게시글 리스트 이미지 연동, 게시글 리스트 줄 맞춤
  src/assets/Svgs/default_image.svg
  src/components/ArticleListItem.jsx
Labels: FEAT

#50 [FIX] 비로그인 시 댓글 막기 및 로그인 화면 유도
  src/pages/ArticleView.jsx
Labels: FIX

#54 [FIX] 로그인/회원가입 페이지 모달 적용
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: FIX

#62 [FEAT] 게시글 페이지네이션 및 모바일 무한 스크롤 적용
  src/api/articleApi.js
  src/components/ArticleListItem.jsx
  src/pages/ArticleList.jsx
Labels: FEAT

#67 [FIX] 헤더 프로필이미지 오타 수정
  src/components/Header.jsx
Labels: FIX

#70 [FEAT] 로그인 이메일/비밀번호 검증 및 에러 메시지 추가
  src/pages/Login.jsx
Labels: FEAT

#75 [REFAC] : API 연동 방식 리팩토링
  src/api/AxiosInstance.js
  src/api/main.js
  src/api/memberApi.js
  src/components/Header.jsx
  src/pages/Main.jsx
Labels: REFAC

#80 [FIX] 댓글 사용자 정보 오류 수정
  src/components/CommentInput.jsx
  src/components/CommetListItem.jsx
  src/pages/ArticleView.jsx
Labels: FIX

#86 [FIX] 페이지네이션 오류 수정
  src/api/articleApi.js
Labels: FIX

#88 [FIX] : 셀렉트 박스 버그 수정
  src/components/SelectBox.jsx
  src/pages/Main.jsx
Labels: FIX

#90 [FEAT] : 토큰 만료 처리
  src/api/AxiosInstance.js
  src/api/memberApi.js
  src/components/Header.jsx
  src/pages/Main.jsx
Labels: FEAT

#95 [FEAT] 회원정보 수정 정규식 검증 로직 추가 및 팝업 메시지 수정
  src/pages/MyPage.jsx
Labels: FEAT

#106 [SETTING] : 파비콘 설정
  index.html
  public/favicon.png
  public/vite.svg
Labels: SETTING

#110 [FIX] 댓글 줄바꿈 설정
  src/components/CommetListItem.jsx
Labels: FIX

#112 [FIX] 게시글 작성 모바일 페이지 카테고리 오류 수정
  src/components/SelectBox.jsx
  src/pages/ArticleView.jsx
  src/pages/ArticleWrite.jsx
Labels: FIX
